### ISSUE TITLE
Problems getting dog facts

### ISSUE THREAD

**Issue by FroogalTheDragon** [CodeCanna/petfacts#1]
This error is returned when trying to display a dog fact:
```
Invalid repsonse recieved, got Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/petfacts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/petfacts/petfacts.py", line 60, in main
    print(f"Random Dog Fact: {dog_fact()}")
  File "/usr/local/lib/python3.9/dist-packages/petfacts/petfacts.py", line 35, in dog_fact
    return fact[0]['fact']
UnboundLocalError: local variable 'fact' referenced before assignment

```

**Comment by FroogalTheDragon** [comment]
It would seem that the dog fact API hosted at `https://dog-facts-api.herokuapp.com/api/v1/resources/dogs?number=1` is offline; which would explain why the dog fact feature of this application isn't functioning.

Until this API is back online this feature won't work, if anyone has another dog fact API that's free please post it here.

**Comment by FroogalTheDragon** [comment]
Looks like its back up!  Hooray!
